# Docker Compose file for Vapor
#
# Install Docker on your system to run and test
# your Vapor app in a production-like environment.
#
# Note: This file is intended for testing and does not
# implement best practices for a production deployment.
#
# Learn more: https://docs.docker.com/compose/reference/
#
#   Build images: docker compose build
#      Start app: docker compose up app
#       Stop all: docker compose down
#

x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-debug}

services:
  postgres:
    image: postgres:latest
    container_name: chargeback_postgres
    environment:
      POSTGRES_USER: chargeback_admin
      POSTGRES_PASSWORD: chargeback-app-db-admin
      POSTGRES_DB: chargeback_app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chargeback_admin -d chargeback_app_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: backend:latest
    build:
      context: .
    environment:
      <<: *shared_environment
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    # user: '0' # uncomment to run as root for testing purposes even though Dockerfile defines 'vapor' user.
    command:
      [
        "serve",
        "--env",
        "production",
        "--hostname",
        "0.0.0.0",
        "--port",
        "8080",
      ]

volumes:
  postgres_data:
